# Generated by Django 4.2.2 on 2023-06-06 09:40

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='img_branches')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Branch Name')),
                ('branch_contact_number_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Branch number')),
                ('branch_contact_number_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Branch number')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Branch location')),
            ],
            options={
                'verbose_name': 'Add your branch',
                'verbose_name_plural': 'Add your branches',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='gallery')),
            ],
            options={
                'verbose_name': 'Add gallery',
                'verbose_name_plural': 'Add galleries',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='Menus')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('ClassName', models.CharField(choices=[('starters', 'starters'), ('main-dishes', 'main-dishes'), ('drinks', 'drinks'), ('desserts', 'desserts'), ('icecream', 'icecream')], max_length=50, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage', models.CharField(blank=True, max_length=60, null=True)),
                ('review', tinymce.models.HTMLField(blank=True, max_length=300, null=True)),
                ('Guest', versatileimagefield.fields.VersatileImageField(upload_to='review_guest')),
                ('Guest_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Guest Name')),
            ],
        ),
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='CarouselSlide')),
                ('prev_slide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_slides', to='web.carouselslide')),
            ],
            options={
                'verbose_name': 'Home Slide image',
                'verbose_name_plural': 'Home Slide images',
            },
        ),
    ]
